name: Docker Build and Push

on:
  push:
    branches: [ main ]  # 触发构建的分支
  repository_dispatch:
    types: [sync]       # 用于手动触发上游同步
  workflow_dispatch:    # 允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 步骤1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤2: 设置构建元数据
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 步骤3: 登录Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 步骤4: 解析镜像标签
      - name: Generate tags
        id: tags
        run: |
          SHA_SHORT=$(git rev-parse --short=8 HEAD)
          DATE=$(date +'%Y%m%d')
          echo "SHA=${SHA_SHORT}" >> $GITHUB_OUTPUT
          echo "TAG=${DATE}-${SHA_SHORT}" >> $GITHUB_OUTPUT

      # 步骤5: 构建并推送镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .   # Dockerfile所在目录
          push: true   # 构建后自动推送
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:${{ steps.tags.outputs.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
